{% set name = "stonerplots" %}


package:
  name: {{ name|lower }}
  version: {{ environ.get('VERSION', '') }}
source:
  path: ..

build:
  noarch: python
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  host:
    - matplotlib >=3.6
    - python >=3.10
    - setuptools >=65.0
    - setuptools-scm >=8.0
    - numpy
    - pip
  run:
    - matplotlib >=3.6
    - numpy
    - python >=3.10

test:
  imports:
    - stonerplots
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stonerlab/stonerplots
  summary: This is a fork of scienceplots and provides a range of matplotlib styles for plotting physics...
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gb119
